version: '3'

services:
  pg-tasks:
    image: :9.6
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:
      - "16543:80"
    depends_on:
      -  pg-tasks
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge


