pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                echo 'Hello World'

                script {
                     docker.build("my-image:${env.BUILD_ID}", "-f api/tests/Dockerfile api")
                }
            }
        }
    }
}