pipeline {
    agent any
    stages {
        stage('Teste unitário') {
            steps {
                script {
                     docker.build("api-test:${env.BUILD_ID}", "-f api/tests/Dockerfile api")
                }
            }
        }
        stage('Build') {
            steps {
                script {
                     docker.build("api-dev:${env.BUILD_ID}", "-f api/Dockerfile api")
                }
            }
        }
    }
}